// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gameinstall} from '../models';

export function FindGameInstalls():Promise<Array<gameinstall.GameInstallInfo>>;

export function GetOrCreateInstallList(arg1:boolean):Promise<Array<gameinstall.GameInstallInfo>>;
