// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindGameInstalls() {
  return window['go']['gameinstall']['GameInstallation']['FindGameInstalls']();
}

export function GetOrCreateInstallList(arg1) {
  return window['go']['gameinstall']['GameInstallation']['GetOrCreateInstallList'](arg1);
}
