// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPrecompiledScriptCache(arg1) {
  return window['go']['gameinstall']['PrecompiledScript']['GetPrecompiledScriptCache'](arg1);
}

export function GetPrecompiledScriptCacheSize(arg1) {
  return window['go']['gameinstall']['PrecompiledScript']['GetPrecompiledScriptCacheSize'](arg1);
}

export function IsPrecompiledScriptActive(arg1) {
  return window['go']['gameinstall']['PrecompiledScript']['IsPrecompiledScriptActive'](arg1);
}

export function TogglePrecompiledScriptStatus(arg1, arg2) {
  return window['go']['gameinstall']['PrecompiledScript']['TogglePrecompiledScriptStatus'](arg1, arg2);
}
