// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gameinstall} from '../models';

export function GetPrecompiledScriptCache(arg1:gameinstall.GameInstallInfo):Promise<string>;

export function GetPrecompiledScriptCacheSize(arg1:gameinstall.GameInstallInfo):Promise<number>;

export function IsPrecompiledScriptActive(arg1:gameinstall.GameInstallInfo):Promise<boolean>;

export function TogglePrecompiledScriptStatus(arg1:gameinstall.GameInstallInfo,arg2:boolean):Promise<boolean>;
