// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadBrowsableModList() {
  return window['go']['mod']['Mod']['DownloadBrowsableModList']();
}

export function DownloadModWithProgress(arg1, arg2, arg3) {
  return window['go']['mod']['Mod']['DownloadModWithProgress'](arg1, arg2, arg3);
}

export function GetBrowsableMods(arg1) {
  return window['go']['mod']['Mod']['GetBrowsableMods'](arg1);
}

export function GetLocalMods(arg1) {
  return window['go']['mod']['Mod']['GetLocalMods'](arg1);
}

export function GetModDetails(arg1) {
  return window['go']['mod']['Mod']['GetModDetails'](arg1);
}

export function GetModDetailsFromFile(arg1) {
  return window['go']['mod']['Mod']['GetModDetailsFromFile'](arg1);
}

export function GetModDetailsFromURL(arg1) {
  return window['go']['mod']['Mod']['GetModDetailsFromURL'](arg1);
}

export function GetVisibleModDetails(arg1) {
  return window['go']['mod']['Mod']['GetVisibleModDetails'](arg1);
}
