// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mod} from '../models';

export function DownloadModList():Promise<boolean>;

export function GetAvailableMods(arg1:string):Promise<Array<mod.ModSummary>>;

export function GetModDetails(arg1:mod.ModSummary):Promise<mod.ModDetails>;

export function GetVisibleModDetails(arg1:Array<mod.ModSummary>):Promise<Array<mod.ModDetails>>;
