// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mod} from '../models';

export function DownloadBrowsableModList():Promise<boolean>;

export function DownloadModWithProgress(arg1:string,arg2:string,arg3:any):Promise<void>;

export function GetBrowsableMods(arg1:string):Promise<Array<mod.ModSummary>>;

export function GetLocalMods(arg1:string):Promise<Array<mod.ModSummary>>;

export function GetModDetails(arg1:mod.ModSummary):Promise<mod.ModDetails>;

export function GetModDetailsFromFile(arg1:mod.ModSummary):Promise<mod.ModDetails>;

export function GetModDetailsFromURL(arg1:mod.ModSummary):Promise<mod.ModDetails>;

export function GetVisibleModDetails(arg1:Array<mod.ModSummary>):Promise<Array<mod.ModDetails>>;
