// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadModList() {
  return window['go']['mod']['Mod']['DownloadModList']();
}

export function GetAvailableMods(arg1) {
  return window['go']['mod']['Mod']['GetAvailableMods'](arg1);
}

export function GetModDetails(arg1) {
  return window['go']['mod']['Mod']['GetModDetails'](arg1);
}

export function GetVisibleModDetails(arg1) {
  return window['go']['mod']['Mod']['GetVisibleModDetails'](arg1);
}
